### ISSUE TITLE
Question: bindgen run time

### ISSUE THREAD

**Issue by dcsobral** [onelson/jq-sys#5]
If I understand this correctly, bindgen was run by hand, and the bindings then committed. Why not run bindgen at build time instead?

**Comment by onelson** [comment]
Yeah, that's a valid question.

For me, it was advantageous to have fewer moving pieces during the build, especially during early development where I was referring to the bindgen output constantly.

Bindgen requires having libclang and friends available, which can mean a hefty download, sometimes distro package repo addition if you're working from an older linux release. It seemed like a nice convenience to "just have the output" in that respect. Add to that the signatures for jq 1.6 (the only version I boast support for currently) are not likely to change over time, it seemed like a reasonable way to go.

There's a git submodule for the jq source in this repo at this point, so should be fairly trivial to switch this over to generate the bindings from the headers at build time if that's preferred for some reason.

**Comment by dcsobral** [comment]
Well, since I was using bindgen at build time before I found your crates, I can understand the issues on development, though I assumed it would be mitigated by having it on a separate crate. I had not thought of the implications for building downstream, though.

**Comment by dcsobral** [comment]
Why is jq a submodule of both jq-sys and jq-src?

**Comment by onelson** [comment]
The submodule in jq-src is used to build libjq, and the submodule in jq-sys is just there for running bindgen against.
